# The main config file for your Jekyll template


# Site settings
title: Alexander Jung              # used for the html title of every page
desc: Professional website of Alexander Jung
url: https://alexjungaalto.github.io/      # put your website hosting url here


# Meta settings
email: alex.jung@aalto.fi
author: Alexander Jung
twitter_username: alexjungaalto
github_username: alexjungaalto
github_source: alexjungaalto.github.io

# Put your ga tracking code below
google_analytics: 'UA-XXXXXXXX-X'

# Navigation settings
# Used to define the navigation menu items
# > Title is the tile of the navigation item, url the url and desc is the tooltip
navigation:
  - title: Textbook "Machine Learning. The Basics"
    url: https://alexjungaalto.github.io/MLBasicsBook.pdf
    desc: Draft for Textbook "Machine Learning. The Basics" 
  - title: YouTube Channel
    url: https://www.youtube.com/channel/UC_tW4Z_GfJ2WCnKDtwMuDUA
    desc: My YouTube channel
  - title: LinkedIn
    url: https://www.linkedin.com/in/aljung/
    desc: My LinkedIn account

# Markdown parser settings
markdown: kramdown
theme: minima

