title: Alexander Jung (AJ)
description: Machine Learning Evangelist
author:
  name: Alexander Jung
  nickname: alexjungaalto
  twitter: alexjungaalto
#hostname: jimeh.me # used to determine if google analytics should be triggered
#url: https://jimeh.me # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: /:title/


# stuff for jekyll-seo-tag
social:
  name: Alex Jung
  links:
    - https://twitter.com/alexjungaalto
    - https://github.com/alexjungaalto
    - https://www.linkedin.com/in/aljung/
    - https://www.youtube.com/channel/UC_tW4Z_GfJ2WCnKDtwMuDUA
    - https://alexjungaalto.github.io/MLBasicsBook.pdf

twitter:
  username: alexjungaalto

# Navigation settings
# Used to define the navigation menu items
# > Title is the tile of the navigation item, url the url and desc is the tooltip
navigation:
  - title: Textbook "Machine Learning. The Basics"
    url: https://alexjungaalto.github.io/MLBasicsBook.pdf
    desc: Draft for Textbook "Machine Learning. The Basics" 
  - title: YouTube Channel
    url: https://www.youtube.com/channel/UC_tW4Z_GfJ2WCnKDtwMuDUA
    desc: My YouTube channel
  - title: LinkedIn
    url: https://www.linkedin.com/in/aljung/
    desc: My LinkedIn account


# additional stuff
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      layout: "default"


# Site settings
title: Alexander Jung              # used for the html title of every page
desc: Professional website of Alexander Jung
url: https://alexjungaalto.github.io/      # put your website hosting url here









